spring.application.name=connections-service

server.port=9040

server.servlet.context-path=/connections

# neo4j connection

spring.neo4j.uri=neo4j+s://7683b821.databases.neo4j.io
spring.neo4j.authentication.username=7683b821
spring.neo4j.authentication.password=g-S74WSK2QYHMOy5Ag4GD8hSblckwWMm_Ar2yhwUzLQ

# Optional: Connection Pool (good practice)
spring.neo4j.pool.max-connection-pool-size=50

# Optional: Logging
logging.level.org.springframework.data.neo4j=DEBUG

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include= *